config/routes.rb
Brs2::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :positions
  resources :teams
  resources :projects
  resources :skills
  resources :activities
  resources :reports
  namespace :admin do
  	match "/signin", to: "sessions#new", via: "get"
    match "/signout", to: "sessions#destroy", via: "delete"
  	resources "sessions", only: [:new, :create, :destroy]
  	resources "users"
    match "csvs", to: "csvs#index", via: :get
    match "csvs/import", to: "csvs#import", via: :post
    match "csvs/export", to: "csvs#export", via: :get
    resource "members"
  end
  root "static_pages#home"
  match "/help", to: "static_pages#help", via: "get"
  match "/about", to: "static_pages#about", via: "get"
  match "/contact", to: "static_pages#contact", via: "get"
  match "/signin",  to: "sessions#new",         via: "get"
  match "/signout", to: "sessions#destroy",     via: "delete"
end

app/models/position.rb
class Position < ActiveRecord::Base
  has_many :users, dependent: :destroy
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
  validates :short_name, presence:true, length: { maximum: 10 }, uniqueness: { case_sensitive: false }
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController

  def show
    @position = Position.find params[:id]
  end

  def new
    @position = Position.new
  end

  def destroy
    position= Position.find(params[:id])
    Activity.create( time: position.created_at, action: " Delete Position", 
                       user: current_user.id, description: position.name)
    position.destroy
    flash[:success] = "Position deleted."
    redirect_to positions_path
  end

  def index
    @positions = Position.paginate page: params[:page]
  end

  def edit
    @position = Position.find params[:id]
  end

  def update
    @position = Position.find params[:id]
    if @position.update_attributes position_params
      Activity.create( time: @position.created_at, action: " Update Position", 
                       user: current_user.id, description: @position.name)
      flash[:success] = "Update done!"
      redirect_to positions_path
    else
      render 'edit'
    end
  end

  def create
    @position = Position.new position_params
    if @position.save
      flash[:success] = "Create done!"
      redirect_to positions_path
      Activity.create( time: @position.created_at, action: " Create Position", 
                       user: current_user.id, description: @position.name)
    else
      render 'new'
    end
  end  

  private
    def position_params
      params.require(:position).permit(:name, :short_name)    
    end
end

app/views/positions/_position.html.erb
<li>
  <span class="short_name"><%= position.short_name %><span>
  <span class="name"> <%= position.name %></span>
   <%= link_to "delete", position, method: :delete,
                                  data: { confirm: "You sure?" } %>
   <%= link_to "edit", edit_position_path(position.id) %>
</li>

app/views/positions/edit.html.erb
<% provide(:title, 'Edit Position') %>
<h1>Edit Position </h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@position) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :short_name %>
      <%= f.text_field :short_name %>

      <%= f.submit "Save Changes ", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/positions/index.html.erb
<% provide(:title, 'All Positions') %>
<h1>All Positions</h1>
<%= will_paginate %>

<ul class="positions">
  <% @positions.each do |position| %>
    <%= render position%>
  <% end %>
</ul>

<%= will_paginate %>

<span> <%= link_to "Create new Position", new_position_path %></span>

app/views/positions/new.html.erb
<% provide(:title, 'new Position') %>
<h1>Make new Position </h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@position) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :short_name %>
      <%= f.text_field :short_name %>

      <%= f.submit "Create Position", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>