config/routes.rb
Brs2::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :positions
  resources :teams
  resources :projects
  resources :skills
  resources :activities
  resources :reports
  namespace :admin do
  	match "/signin", to: "sessions#new", via: "get"
    match "/signout", to: "sessions#destroy", via: "delete"
  	resources "sessions", only: [:new, :create, :destroy]
  	resources "users"
    match "csvs", to: "csvs#index", via: :get
    match "csvs/import", to: "csvs#import", via: :post
    match "csvs/export", to: "csvs#export", via: :get
    resource "members"
  end
  root "static_pages#home"
  match "/help", to: "static_pages#help", via: "get"
  match "/about", to: "static_pages#about", via: "get"
  match "/contact", to: "static_pages#contact", via: "get"
  match "/signin",  to: "sessions#new",         via: "get"
  match "/signout", to: "sessions#destroy",     via: "delete"
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :user_projects
  has_many :users, through: :user_projects
  belongs_to :team
  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	 def show
    @project = Project.find params[:id]
  end

  def new
    @project = Project.new
  end

  def destroy
    project= Project.find(params[:id]).destroy
    Activity.create( time: Time.now, action: " Delete Project", 
                       user: current_user.id, description: project.name)
    flash[:success] = "project deleted."
    redirect_to projects_path
  end

  def index
    @projects = Project.paginate page: params[:page]
  end

  def edit
    @project = Project.find params[:id]
  end

  def update
    @project = Project.find params[:id]
    if @project.update_attributes project_params
      Activity.create( time: Time.now, action: " Delete Project", 
                       user: current_user.id, description: @project.name)
      flash[:success] = "Update done!"
      redirect_to projects_path
    else
      render 'edit'
    end
  end

  def create
    @project = Project.new project_params
    if @project.save
      Activity.create( time: Time.now, action: " Create Project", 
                       user: current_user.id, description: @project.name)
      redirect_to projects_path
    else
      render 'new'
    end
  end  

  private
    def project_params
      params.require(:project).permit(:name, :short_name, :start_date, :end_date, :id_leader)    
    end
end    

app/views/projects/_error_projects.html.erb
<% if @project.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@project.errors.count, "error") %>.
    </div>
    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/projects/_project.html.erb
<li>
  <span class="short_name"><%= project.short_name %><span>
  <span class="name"> <%= project.name %></span>
</li>
<li>
  <span class="start_date"><%= project.start_date %><span>
  <span class="end_date"> <%= project.end_date %></span>

  <%= link_to "delete", project, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <%= link_to "edit", edit_project_path(project.id) %>
</li>

app/views/projects/edit.html.erb
<% provide(:title, 'Edit Project') %>
<h1>Edit Project </h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@project) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :short_name %>
      <%= f.text_field :short_name %>

      <%= f.label :start_date %>
      <%= f.text_field :start_date %>

      <%= f.label :end_date %>
      <%= f.text_field :end_date %>

      <%= f.label :id_leader %>
      <%= f.text_field :id_leader %>

      <%= f.submit "Save Changes ", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/projects/index.html.erb
<% provide(:title, 'All projects') %>
<h1>All Projects</h1>
<%= will_paginate %>

<ul class="Projects">
  <% @projects.each do |project| %>
    <%= render project%>
  <% end %>
</ul>

<%= will_paginate %>

<span> <%= link_to "Create new project", new_project_path %></span>

app/views/projects/new.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@project) do |f| %>
      <%= render 'shared/error_projects' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :short_name %>
      <%= f.text_field :short_name %>

      <%= f.label :start_date %>
      <%= f.text_field :start_date %>

      <%= f.label :end_date %>
      <%= f.text_field :end_date %>

      <%= f.label :id_leader %>
      <%= f.text_field :id_leader %>

      <%= f.submit "Create Project ", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>